replacements = {
    "60'S": "60s",
    "60S": "60s",
    "60s Rock": "60s",
    "Pop 60's": "60s Pop",
    "70'S": "70s",
    "Rock - 70's": "70s",
    "70's Pop": "70s Pop",
    "80S": "80s",
    "80s Remixes": "80s",
    "Dance/80s/Remix": "80s",
    "Eighties": "80s",
    "80'S": "80s Pop",
    "Pop 80s": "80s Pop",
    "A capella": "Acappella",
    "A cappella": "Acappella",
    "A Cappella": "Acappella",
    "Acapella": "Acappella",
    "Accapella": "Acappella",
    "Adult Contemporar": "Adult Contemporary",
    "Alt": "Alternative",
    "Alt Rock": "Alternative",
    "Alt-Rock": "Alternative",
    "Alt. Pop/Rock": "Alternative",
    "Alt. Rock": "Alternative",
    "Alternative - GBV": "Alternative",
    "Alternative & Punk": "Alternative",
    "Alternative Musik": "Alternative",
    "Alternative Pop": "Alternative",
    "Alternative Pop/Rock": "Alternative",
    "Alternative Rock": "Alternative",
    "Alternative, Garage, Rock": "Alternative",
    "Alternative/Rock|Pop": "Alternative",
    "AlternRock": "Alternative",
    "Classic Rock - Alternative": "Alternative",
    "General Alternative": "Alternative",
    "Indie / Alternative": "Alternative",
    "Indie Alternative": "Alternative",
    "Indie Alternative Rock": "Alternative",
    "Indie and Alternative": "Alternative",
    "Latin Alternative": "Alternative",
    "Ambient Electronic": "Ambient",
    "Ambient/Dream Pop": "Ambient",
    "AmbientAmbient": "Ambient",
    "Chillwave/Ambient": "Ambient",
    "DARK AMBIENT / DRONE / METAL": "Ambient",
    "Dementia, Memories, Ambient": "Ambient",
    "Baile": "Baille Funk",
    "Baile funk": "Baille Funk",
    "Brazilian Funk": "Baille Funk",
    "Favela Baile Funk": "Baille Funk",
    "BlueGrass": "Bluegrass",
    "Early Banjo": "Bluegrass",
    "Progressive Bluegrass": "Bluegrass",
    "Acoustic Blues": "Blues",
    "Blues Rock": "Blues",
    "Blues/R&B": "Blues",
    "Tom Waits Covers": "Blues",
    "Voodoo Blues": "Blues",
    "Bossa": "Bossa Nova",
    "Brit Pop & Rock": "BritPop",
    "Britpop": "BritPop",
    "Indie Rock /  Brit - Pop": "BritPop",
    "Broadway & Vocalists": "Broadway",
    "Musical": "Broadway",
    "Musicals": "Broadway",
    "Showtunes": "Broadway",
    "Irish Folk": "Celtic",
    "Children": "Children’s Music",
    "Children's": "Children’s Music",
    "Christian & Gospel": "Christian",
    "Christian Gangsta Rap": "Christian",
    "Christian Rap": "Christian",
    "Contemporary Christian": "Christian",
    "Christmas Music": "Christmas",
    "Christmas: Pop": "Christmas",
    "ChristmasChristmas": "Christmas",
    "Mixmas": "Christmas",
    "Xmas": "Christmas",
    "Hippie Rock": "Classic Rock",
    "General Classical": "Classical",
    "Indie Classical": "Classical",
    "Opera": "Classical",
    "Opera & Vocal": "Classical",
    "Orchestra": "Classical",
    "Symphony": "Classical",
    "Comedy Rock": "Comedy",
    "Alt Country": "Country",
    "Alt.-Country": "Country",
    "Alternative Country": "Country",
    "Classic Country": "Country",
    "Country and Folk": "Country",
    "Country Country/Bluegrass Outlaw Country Pop": "Country",
    "Country Pop": "Country",
    "Country Rock": "Country",
    "Country-Rock": "Country",
    "Country/Pop/Rock/R&B/Soul": "Country",
    "Country/Rock": "Country",
    "Countrysex": "Country",
    "Psychedelic Country": "Country",
    "Alternative Dance": "Dance",
    "Club": "Dance",
    "Dance & DJ": "Dance",
    "Dance & House": "Dance",
    "Dance Hall": "Dance",
    "Dance Pop": "Dance",
    "Dance/Electro/Funky": "Dance",
    "Dancehall": "Dance",
    "Eurodance": "Dance",
    "Indie / Dance / Electro / Party Pop": "Dance",
    "Indie Dance": "Dance",
    "Indie Dance / Nu Disco": "Dance",
    "Indie Dance/Nu Disco": "Dance",
    "Indie Disco": "Dance",
    "Indie Electro Dance": "Dance",
    "Nu Disco / Indie Dance": "Dance",
    "Disco / Nu Disco / Re-Edits": "Disco",
    "Disco / Re-Edit": "Disco",
    "Disco House": "Disco",
    "Disco re-edits": "Disco",
    "Disco-funk": "Disco",
    "Disco, House": "Disco",
    "InDisco": "Disco",
    "Italo Disco": "Disco",
    "Nu-Disco": "Disco",
    "NuDisco": "Disco",
    "Rock / Re Edit / Disco": "Disco",
    "Rock dance": "Disco",
    "Rock Disco Americana": "Disco",
    "Doo-Wop": "Doo Wop",
    "Dream Pop & Shoegazer": "Dream Pop",
    "DreamPop": "Dream Pop",
    "Ethereal": "Dream Pop",
    "Alternative Electronic": "Electronic",
    "Club-House": "Electronic",
    "Club, Electronic, Remix": "Electronic",
    "Club/Electro": "Electronic",
    "Dance / Electronic": "Electronic",
    "Dance/Electronic": "Electronic",
    "Dance/Electronica": "Electronic",
    "DJ Mix, House, Remix": "Electronic",
    "Drum & Bass": "Electronic",
    "Drum and Bass": "Electronic",
    "Drumstep": "Electronic",
    "Dub": "Electronic",
    "Dubstep": "Electronic",
    "Dubstep/Electro": "Electronic",
    "Dubstep/Garage": "Electronic",
    "Electonic": "Electronic",
    "Electric": "Electronic",
    "Electro": "Electronic",
    "Electro Blues": "Electronic",
    "Electro Fidget": "Electronic",
    "Electro House": "Electronic",
    "Electro Pop": "Electronic",
    "Electro Rap": "Electronic",
    "Electro Rock": "Electronic",
    "Electro-Industrial": "Electronic",
    "Electro-pop": "Electronic",
    "Electro-Pop": "Electronic",
    "Electro-Rock": "Electronic",
    "Electro-Synth": "Electronic",
    "Electro/Dance": "Electronic",
    "Electroclash": "Electronic",
    "ElectroHouse": "Electronic",
    "Electronic / Hip Hop": "Electronic",
    "Electronic Pop": "Electronic",
    "Electronic, Funk, Techno": "Electronic",
    "Electronic, House, Ambient": "Electronic",
    "Electronic, House, Techno": "Electronic",
    "Electronic, Indie, Pop": "Electronic",
    "Electronic, Nu Disco": "Electronic",
    "Electronic, Pop": "Electronic",
    "Electronic,Alternative, Pop": "Electronic",
    "Electronic; Nu-Rave": "Electronic",
    "Electronic/Indie": "Electronic",
    "Electronica": "Electronic",
    "Electronica / Dance": "Electronic",
    "Electronica / Glitch": "Electronic",
    "Electronica & Dance": "Electronic",
    "Electronica and Dance": "Electronic",
    "Electronica/Dance": "Electronic",
    "Electropop": "Electronic",
    "Electrotash": "Electronic",
    "Euro-Techno": "Electronic",
    "Exp. Electro": "Electronic",
    "Freakbeat": "Electronic",
    "Future Jungle": "Electronic",
    "General Electronic": "Electronic",
    "Hardcore Techno": "Electronic",
    "Indie Trance": "Electronic",
    "Indie/Electronic": "Electronic",
    "Musica Electronica": "Electronic",
    "Old School Rave": "Electronic",
    "Pop / Electronic": "Electronic",
    "Post-Modern Electronic Pop": "Electronic",
    "Techno": "Electronic",
    "Techno//House//Live Electronics": "Electronic",
    "Trance": "Electronic",
    "Tribal-Electro": "Electronic",
    "ElectroSwing": "Electroswing",
    "Exotica & Space Age Pop": "Exotica",
    "Tropicalia": "Exotica",
    "Abstract": "Experimental",
    "Avant-Garde": "Experimental",
    "Avante-Garde": "Experimental",
    "Avantgarde": "Experimental",
    "Alt-Folk": "Folk",
    "Alt-Folk, Folk Rock, Indie Pop, Freak Folk": "Folk",
    "Alternative / Folk": "Folk",
    "Contemporary Folk": "Folk",
    "Contemporary U.S. Folk": "Folk",
    "Folk (Singer/Songwriter)": "Folk",
    "Folk / Alt-Country": "Folk",
    "Folk Blues": "Folk",
    "Folk Fusion": "Folk",
    "Folk Punk": "Folk",
    "Folk Rock": "Folk",
    "Folk-Pop": "Folk",
    "Folk-Punk": "Folk",
    "Folk-Rock": "Folk",
    "Folk/Pop": "Folk",
    "Folk/psychfolk": "Folk",
    "Folk/Rock": "Folk",
    "Folk/Singer Songwriter": "Folk",
    "Folklore": "Folk",
    "Folktronica": "Folk",
    "General Folk": "Folk",
    "General Traditional U.S. Folk": "Folk",
    "Indie Folk": "Folk",
    "Indie-Folk": "Folk",
    "Pop-Folk": "Folk",
    "Psychedelic Folk": "Folk",
    "Pop/Folk": "Folk Pop",
    "Francais": "French Pop",
    "Franse pop": "French Pop",
    "Franse Pop": "French Pop",
    "French": "French Pop",
    "Afro Funk": "Funk",
    "Electro Funk": "Funk",
    "Epic Funky Soul": "Funk",
    "Funk Metal": "Funk",
    "Funk/Soul": "Funk",
    "Ghetto Funk": "Funk",
    "Gumbo Funk": "Funk",
    "NO Funk": "Funk",
    "Soul Music/Funk": "Funk",
    "Tropical Funk": "Funk",
    "UK Funky": "Funk",
    "Garage": "Garage Rock",
    "Garage-Rock": "Garage Rock",
    "UK Garage": "Garage Rock",
    "Glam Metal": "Glam",
    "Glam Rock": "Glam",
    "Gospel & Religious": "Gospel",
    "Darkwave": "Goth",
    "Doom": "Goth",
    "Goth Rock": "Goth",
    "Gothic": "Goth",
    "Gothic Ambient": "Goth",
    "Gothic Rock": "Goth",
    "Gothic/Industrial": "Goth",
    "PuGoth": "Goth",
    "Grunge Rock": "Grunge",
    "[Hip-Hop/Rap/Electronic]": "Hip Hop",
    "Alternative Hip-Hop": "Hip Hop",
    "Beatbox": "Hip Hop",
    "Electro Hip Hop": "Hip Hop",
    "Electro Hip-Hop": "Hip Hop",
    "Electro Hip-Hop Soul": "Hip Hop",
    "Electronic/Hip Hop": "Hip Hop",
    "Glitchhop": "Hip Hop",
    "Hip HOp": "Hip Hop",
    "Hip Hop / Electro": "Hip Hop",
    "Hip Hop/Rap": "Hip Hop",
    "Hip Hop/Soul": "Hip Hop",
    "Hip- Hop": "Hip Hop",
    "Hip-Hop/Electronic": "Hip Hop",
    "Hip-Hop/R&B": "Hip Hop",
    "Hip-Hop/Rap": "Hip Hop",
    "HipHop": "Hip Hop",
    "Hop Hop": "Hip Hop",
    "Rap & Hip Hop": "Hip Hop",
    "Rap & Hip-Hop": "Hip Hop",
    "Trap": "Hip Hop",
    "Trap n' Bass": "Hip Hop",
    "Uptempo Southern Rap": "Hip Hop",
    "Junkyard Country": "Honky Tonk",
    "Acid": "House",
    "Acid House": "House",
    "Acid Jazz": "House",
    "Deep House": "House",
    "Dope House": "House",
    "Ghetto House": "House",
    "House / Electro": "House",
    "House, Pop, Techno": "House",
    "House/Electro": "House",
    "House/Electronic": "House",
    "House/Krunk/Mashup": "House",
    "Housey": "House",
    "Hs": "House",
    "Jungle": "House",
    "Progressive House": "House",
    "Progressive-House": "House",
    "Tech House": "House",
    "White Label, House, 70s Remix": "House",
    "]Indie": "Indie",
    "Alternative & Indie": "Indie",
    "Indie Pop/Rock": "Indie",
    "Indie Rock, Electro Pop": "Indie Pop",
    "General Indie Rock": "Indie Rock",
    "Indie, Post-Rock": "Indie Rock",
    "Industrial EBM": "Industrial",
    "Industrial Metal": "Industrial",
    "Industrial Rock": "Industrial",
    "Techno-Industrial": "Industrial",
    "Easyjazzanova": "Jazz",
    "Fusion": "Jazz",
    "General Jazz": "Jazz",
    "Gypsy Jazz": "Jazz",
    "Jazz & Bluegrass": "Jazz",
    "Jazz Funk": "Jazz",
    "Jazz Rock": "Jazz",
    "Jazz vocal": "Jazz",
    "Jazz Vocal": "Jazz",
    "Jazz Vocal Male": "Jazz",
    "Jazz Vocals": "Jazz",
    "Jazz, early": "Jazz",
    "Jazz/ Bebop/Blues": "Jazz",
    "Jazz/Blues": "Jazz",
    "Jazz+Funk": "Jazz",
    "Jazzdance": "Jazz",
    "Jazzz..": "Jazz",
    "Mardi Gas": "Jazz",
    "NO Jazz": "Jazz",
    "Nu Jazz": "Jazz",
    "Nu-Jazz": "Jazz",
    "Alternativo & Rock Latino": "Latin",
    "Latino": "Latin",
    "Mariachi": "Latin",
    "Pop Latino": "Latino",
    "Down Tempo": "Lo-Fi",
    "Lo-fi/Lounge": "Lo-Fi",
    "Smooth": "Lo-Fi",
    "The New LoFi": "Lo-Fi",
    "General Neo-Lounge": "Lounge",
    "Halloween/Mashups": "Mashup",
    "Mash": "Mashup",
    "Mash Up": "Mashup",
    "Mash up": "Mashup",
    "Mash-Up": "Mashup",
    "Mash-up": "Mashup",
    "Mash-up": "Mashup",
    "MashUp": "Mashup",
    "MASHUP": "Mashup",
    "Mashups": "Mashup",
    "Sondheim Meets Bright Eyes": "Mashup",
    "80's Metal": "Metal",
    "Alternative Metal": "Metal",
    "Black Metal": "Metal",
    "Death Metal": "Metal",
    "Hard Rock & Metal": "Metal",
    "Heavy Metal": "Metal",
    "Nu Metal": "Metal",
    "Progressive Metal": "Metal",
    "Sludge Metal": "Metal",
    "Thrash Metal": "Metal",
    "Geek": "NerdCore",
    "Nerd Core": "NerdCore",
    "Nerd Rock": "NerdCore",
    "Nerdcore": "NerdCore",
    "Nerdcore Hip-Hop": "NerdCore",
    "General New Age": "New Age",
    "New Wave Tunes Blog": "New Wave",
    "New Wave, Minimal": "New Wave",
    "Parody": "Novelty",
    "Classic Pop": "Pop",
    "Classic Pop Vocals": "Pop",
    "Dance-Pop": "Pop",
    "General Pop": "Pop",
    "Indie-Pop": "Pop",
    "Indie-pop": "Pop",
    "Indiepop": "Pop",
    "No Pain in Pop": "Pop",
    "Noise Pop": "Pop",
    "Noise-Pop": "Pop",
    "Post-Pop": "Pop",
    "Power Pop": "Pop",
    "Psychedelic Pop": "Pop",
    "Sunshine Pop": "Pop",
    "Super Pop": "Pop",
    "Top 40": "Pop",
    "Twee Pop": "Pop",
    "Noisy Post-Punk": "Post Punk",
    "Post-Punk": "Post Punk",
    "Postpunk": "Post Punk",
    "Postpunk / Death Rock": "Post Punk",
    "Proto-Punk": "Post Punk",
    "British Psychedelia": "Psychedelic Rock",
    "Psych Rock": "Psychedelic Rock",
    "Psychedelia": "Psychedelic Rock",
    "Psychedelic": "Psychedelic Rock",
    "Psychrock": "Psychedelic Rock",
    "Psychrock / Bluesrock": "Psychedelic Rock",
    "7Inchpunk.Com": "Punk",
    "Alt / Indie / Punk": "Punk",
    "Alt / Indie / Punk/Acoustic": "Punk",
    "Anarchopunk": "Punk",
    "Garage Punk": "Punk",
    "Gypsy Punk": "Punk",
    "Hardcore Punk": "Punk",
    "Indie Punk": "Punk",
    "Neo-Noir Punk": "Punk",
    "Old School Punk": "Punk",
    "Pop Punk": "Punk",
    "Pop-Punk": "Punk",
    "Punk Cabaret": "Punk",
    "Punk Pop": "Punk",
    "Punk Rock": "Punk",
    "Punk]": "Punk",
    "Punk/Celtic": "Punk",
    "U.K. Punk": "Punk",
    "Classic Soul/R&B": "R&B",
    "Dance R&B": "R&B",
    "General R&B": "R&B",
    "Motown": "R&B",
    "New Jack City": "R&B",
    "New Orleans R&B": "R&B",
    "R and B": "R&B",
    "R&B/Soul": "R&B",
    "Rap/R&B": "R&B",
    "RnB": "R&B",
    "Soul and R&B": "R&B",
    "Soul And R&B": "R&B",
    "Rap Francais": "Rap",
    "Rap Metal": "Rap",
    "[Rock]": "Rock",
    "Adult Pop-Rock": "Rock",
    "Alternative/Indie/Rock": "Rock",
    "General Mainstream Rock": "Rock",
    "General Rock": "Rock",
    "Hardrock": "Rock",
    "Indie rock": "Rock",
    "Indie-Rock": "Rock",
    "Indie/Rock": "Rock",
    "Indierock": "Rock",
    "Irish Rock": "Rock",
    "Latin Rock": "Rock",
    "Modern Rock": "Rock",
    "Noise-Rock": "Rock",
    "Paul McCartney": "Rock",
    "Pop Rock": "Rock",
    "Pop/Rock": "Rock",
    "Post Rock": "Rock",
    "Post-Rock": "Rock",
    "Rock 'n' Roll": "Rock",
    "Rock / Blues": "Rock",
    "Rock / Rock & Roll / Instrumental Rock": "Rock",
    "Rock & Roll": "Rock",
    "Rock n Roll": "Rock",
    "Rock Remix": "Rock",
    "Rock, Folk": "Rock",
    "Rock, Soft Rock, Country-Rock": "Rock",
    "Rock/Classic Rock": "Rock",
    "Rock/Dance": "Rock",
    "Rock/Shoegaze": "Rock",
    "RockNRoll": "Rock",
    "Swamp Rock": "Rock",
    "TropRock": "Rock",
    "Salsa y Tropical": "Salsa",
    "Ska Punk": "Ska",
    "Ska Revival": "Ska",
    "Ska/Rock Steady": "Ska",
    "Classic Soul": "Soul",
    "Latin Soul": "Soul",
    "Northern Soul": "Soul",
    "Soul / Rock": "Soul",
    "Soul pop": "Soul",
    "BSG-Soundtrack": "Soundtrack",
    "Film": "Soundtrack",
    "Film Score": "Soundtrack",
    "Film Soundtrack": "Soundtrack",
    "General Film/TV Music": "Soundtrack",
    "General Soundtrack": "Soundtrack",
    "Original Soundtrack": "Soundtrack",
    "OST": "Soundtrack",
    "Sound Track": "Soundtrack",
    "Soundrack": "Soundtrack",
    "Soundtracks": "Soundtrack",
    "Soundtracks/Musicals": "Soundtrack",
    "SoundtrackSoundtrack": "Soundtrack",
    "Sountracks": "Soundtrack",
    "TV Shows": "Soundtrack",
    "TV Theme": "Soundtrack",
    "TV Theme Songs": "Soundtrack",
    "TV Themes": "Soundtrack",
    "Lounge - Spaceage": "Space Age",
    "Outer Space Music": "Space Age",
    "Space": "Space Age",
    "Books & Spoken": "Spoken Word",
    "Poetry": "Spoken Word",
    "Speech": "Spoken Word",
    "Football Songs": "Sports",
    "Hockey Anthems": "Sports",
    "Soccer": "Sports",
    "Surf": "Surf Rock",
    "1930's Swing": "Swing",
    "Western Swing": "Swing",
    "Swing-Hop": "Swing Revival",
    "Synth": "SynthPop",
    "Trip-Hop": "Trip Hop",
    "Pop Singer/SW": "Vocal",
    "Singer / Songwriter": "Vocal",
    "Singer Songwriter": "Vocal",
    "Singer-Songwriter": "Vocal",
    "Singer/Songwriter": "Vocal",
    "African": "World",
    "Ethnic": "World",
    "International": "World",
    "Irish": "World",
    "Italia": "World",
    "Italo": "World",
    "Japan": "World",
    "Other World": "World",
    "World Fusion": "World",
    "World/Ethnic": "World",
    "Psychadelic": "Psychedelic Rock",
    "Downtempo": "Lo-Fi",
    "LoFi": "Lo-Fi",
    "SynthPop": "Synthpop",
    "Prog Rock": "Progressive Rock",
    "Hawaiian Guitar": "Hawaiian",
    "Mash-up": "Mashup",
    "Celtic Rock": "Celtic",
    "Alt": "Alternative",
    "'Rock": "Rock",
    "Surf": "Surf Rock",
    "Hip HOp": "Hip Hop",
    "Cajun": "Zydeco"
}
